# Generated by Django 3.2.5 on 2021-07-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowData',
        ),
    ]
