# Generated by Django 3.2.5 on 2021-07-08 15:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_showdata_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdata',
            name='age',
        ),
        migrations.AddField(
            model_name='showdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showdata',
            name='post',
            field=models.TextField(default=datetime.datetime(2021, 7, 8, 15, 16, 8, 525723, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
