# Generated by Django 3.2.5 on 2021-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210708_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowData',
        ),
    ]
