# Generated by Django 3.2.5 on 2021-07-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showdata',
            options={'ordering': ['-date']},
        ),
    ]
